WIP

diff --git a/bin/grit b/bin/grit
--- a/bin/grit
+++ b/bin/grit
@@ -25,6 +25,8 @@ getBranch () {
     esac
   done
   branch="$(echo "$branch" | sed 's/\*//' | awk '{print $1}')"
+  echo "nope can't do that "
+  exit 1
   echo "$branch"
 }
 
